spring:
  application:
    name: provider

server:
  port: 9000


eureka:
    client:
      healthcheck:
        enabled: true
      service-url:
        defaultZone:
          http://knys:knys@node2:8762/eureka/,http://knys:knys@node1:8761/eureka/,http://knys:knys@node3:8763/eureka/
    instance:
      hostname: node3
      metadata-map:
        company: knys



knys:
  user:
    name: knysbj
    age: 5
    enabled: true
