version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ../data/redis:/data
    command: redis-server --requirepass 123456
    #environment:
    #  - REDIS_PASSWORD=123456
    ports:
      - "6379:6379"
  register:
    container_name: register
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar --server.port=8761" ]
    image: sb-cloud/register
    ports:
      - "8761:8761"
  provider:
    container_name: provider
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar --server.port=8080" ]
    # command: -Dserver.port=9999
    depends_on:
      - register
    image: sb-cloud/provider
    ports:
      - "8000:8080"
    links:
      - register
  consumer:
    container_name: consumer
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar --server.port=8080" ]
    depends_on:
      - register
    image: sb-cloud/consumer
    ports:
      - "8001:8080"
    links:
      - register
      - provider
  gateway:
    container_name: gateway
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar --server.port=8080" ]
    depends_on:
      - register
      - redis
    image: sb-cloud/gateway
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    ports:
      - "9000:8080"
    links:
      - register
      - provider
      - redis