spring:
  application:
    name: provider

server:
  port: 9000


eureka:
    client:
      healthcheck:
        enabled: true
      service-url:
        defaultZone:
          http://knys:knys@register:8761/eureka/
    instance:
      prefer-ip-address: true
      metadata-map:
        company: knys


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

knys:
  user:
    name: knysbj
    age: 5
    enabled: true
