spring:
  application:
    name: register
  security:
    user:
      name: knys
      password: knys
  profiles:
    active: master

# C:\Windows\System32\drivers\etc 添加主机名
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
